"""Public interface for LLM helpers."""
from __future__ import annotations

from bot.config import (
    CWD_PW_API_KEY,
    GEMINI_API_KEY,
    GEMINI_IMAGE_MODEL,
    GEMINI_MAX_OUTPUT_TOKENS,
    GEMINI_MODEL,
    GEMINI_PRO_MODEL,
    GEMINI_TEMPERATURE,
    GEMINI_TOP_K,
    GEMINI_TOP_P,
    GEMINI_VIDEO_MODEL,
    OPENROUTER_API_KEY,
    OPENROUTER_BASE_URL,
    OPENROUTER_ALPHA_BASE_URL,
    OPENROUTER_TEMPERATURE,
    OPENROUTER_TOP_K,
    OPENROUTER_TOP_P,
    ENABLE_JINA_MCP,
    JINA_AI_API_KEY,
    JINA_SEARCH_ENDPOINT,
    JINA_READER_ENDPOINT,
    QWEN_MODEL,
    USE_VERTEX_IMAGE,
    USE_VERTEX_VIDEO,
    VERTEX_IMAGE_MODEL,
    VERTEX_LOCATION,
    VERTEX_PROJECT_ID,
    VERTEX_VIDEO_MODEL,
)

from .clients import get_gemini_client, get_openrouter_client, get_vertex_client
from .gemini import (
    ImageGenerationError,
    call_gemini,
    call_gemini_with_media,
    extract_and_process_image_from_text,
    generate_image_with_gemini,
    generate_image_with_vertex,
    generate_video_with_veo,
    stream_gemini,
    test_gemini_vision,
)
from .media import detect_mime_type, download_media
from .jina_search import jina_search_tool
from .openrouter import (
    call_openrouter,
    parse_gpt_content,
    parse_qwen_content,
)

__all__ = [
    'CWD_PW_API_KEY',
    'GEMINI_API_KEY',
    'GEMINI_IMAGE_MODEL',
    'GEMINI_MAX_OUTPUT_TOKENS',
    'GEMINI_MODEL',
    'GEMINI_PRO_MODEL',
    'GEMINI_TEMPERATURE',
    'GEMINI_TOP_K',
    'GEMINI_TOP_P',
    'GEMINI_VIDEO_MODEL',
    'OPENROUTER_API_KEY',
    'OPENROUTER_BASE_URL',
    'OPENROUTER_ALPHA_BASE_URL',
    'OPENROUTER_TEMPERATURE',
    'OPENROUTER_TOP_K',
    'OPENROUTER_TOP_P',
    'ENABLE_JINA_MCP',
    'JINA_AI_API_KEY',
    'JINA_SEARCH_ENDPOINT',
    'JINA_READER_ENDPOINT',
    'QWEN_MODEL',
    'USE_VERTEX_IMAGE',
    'USE_VERTEX_VIDEO',
    'VERTEX_IMAGE_MODEL',
    'VERTEX_LOCATION',
    'VERTEX_PROJECT_ID',
    'VERTEX_VIDEO_MODEL',
    'ImageGenerationError',
    'call_gemini',
    'call_gemini_with_media',
    'call_openrouter',
    'detect_mime_type',
    'download_media',
    'jina_search_tool',
    'extract_and_process_image_from_text',
    'generate_image_with_gemini',
    'generate_image_with_vertex',
    'generate_video_with_veo',
    'get_gemini_client',
    'get_openrouter_client',
    'get_vertex_client',
    'parse_gpt_content',
    'parse_qwen_content',
    'stream_gemini',
    'test_gemini_vision',
]
